# Generated by Django 5.0 on 2023-12-08 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profils', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='leaderboard',
        ),
    ]
